# -*- coding: utf-8 -*-
import logging
import threading
import time

from odoo import models, fields, api, _

_logger = logging.getLogger(__name__)


class PosOrder(models.Model):
    _inherit = 'pos.order'

    # ---- Stored fields used by the AI server action ----
    # The native Odoo AI engine (ir.actions.server with
    # evaluation_type='ai_computed') reads its prompt placeholders directly
    # from fields on the record. We expose 3 read-only fields holding the
    # context, plus 1 target field where the AI writes its output.

    xibo_thanks_customer = fields.Char(
        string='Xibo: Thank-You Customer',
        readonly=True, copy=False,
        help="Customer display name captured at payment time. Read-only.",
    )
    xibo_thanks_top_product = fields.Char(
        string='Xibo: Thank-You Top Product',
        readonly=True, copy=False,
        help="Most expensive product in the order. Read-only.",
    )
    xibo_thanks_summary = fields.Char(
        string='Xibo: Thank-You Summary',
        readonly=True, copy=False,
        help="Compact one-line summary of the order context for the AI "
             "prompt (e.g. 'Customer: Diana | Top product: Diamond Ring | "
             "Category: Jewelry | Total: 4500 MXN'). Read-only.",
    )
    xibo_thanks_ai_message = fields.Char(
        string='Xibo: Thank-You AI Message',
        readonly=True, copy=False,
        help="The Thank-You message generated by Odoo's native AI engine. "
             "Written by the bundled AI server action.",
    )
    # Anti-double-dispatch flag for the Thank-You broadcast.
    # The hook fires both on create() and on write(state=paid/done/invoiced);
    # this flag guarantees the broadcast goes out exactly once per order.
    xibo_thanks_sent = fields.Boolean(
        string='Xibo Thank-You Sent',
        default=False, copy=False, readonly=True,
        help="Set to True after a successful Thank-You broadcast (either "
             "direct-XMR Camino B or legacy Broadcast Camino A). Prevents "
             "the message from being re-sent on subsequent state changes.",
    )

    def _xibo_should_send_thanks(self):
        self.ensure_one()
        config = self.config_id
        if not (config and config.xibo_thanks_enabled):
            _logger.info("[XIBO POS THANKS] skip (order=%s): thanks NOT enabled on config=%s",
                         self.name, config.name if config else '<none>')
            return False
        if not (config.xibo_server_id and config.xibo_server_id.state == 'connected'):
            _logger.info("[XIBO POS THANKS] skip (order=%s): server not connected (server=%s state=%s)",
                         self.name,
                         config.xibo_server_id.name if config.xibo_server_id else '<none>',
                         config.xibo_server_id.state if config.xibo_server_id else '<no-server>')
            return False
        # Camino B needs thanks_display_ids; Camino A needs the generic displays.
        has_camino_b = bool(config.xibo_thanks_display_ids and config.xibo_thanks_layout_id)
        if not has_camino_b and not config._xibo_has_target_displays():
            _logger.info("[XIBO POS THANKS] skip (order=%s): no targets — camino_b=%s, generic_targets=%s",
                         self.name, has_camino_b, config._xibo_has_target_displays())
            return False
        if not config._xibo_within_active_window():
            _logger.info("[XIBO POS THANKS] skip (order=%s): outside active window",
                         self.name)
            return False
        if self.state not in ('paid', 'done', 'invoiced'):
            _logger.info("[XIBO POS THANKS] skip (order=%s): state=%s not in paid/done/invoiced",
                         self.name, self.state)
            return False
        if config.xibo_thanks_min_amount and self.amount_total < config.xibo_thanks_min_amount:
            _logger.info("[XIBO POS THANKS] skip (order=%s): amount=%s below min=%s",
                         self.name, self.amount_total, config.xibo_thanks_min_amount)
            return False
        if self.xibo_thanks_sent and not self.env.context.get('xibo_skip_sent_check'):
            _logger.info("[XIBO POS THANKS] skip (order=%s): already sent (xibo_thanks_sent=True)",
                         self.name)
            return False
        _logger.info("[XIBO POS THANKS] proceed (order=%s): all checks passed, camino_b=%s",
                     self.name, has_camino_b)
        return True

    def _xibo_collect_thanks_context(self):
        """Build the variables dict for the thank-you message."""
        self.ensure_one()
        config = self.config_id

        # Customer name (privacy-aware)
        if self.partner_id:
            customer_name = self.partner_id._xibo_resolve_display_name()
        else:
            customer_name = _("valued customer")

        # Top product = most expensive line
        top_product_name = ""
        top_product_id = False
        top_category = ""
        product_list = []
        if self.lines:
            sorted_lines = sorted(
                self.lines, key=lambda l: l.price_unit or 0.0, reverse=True
            )
            top_line = sorted_lines[0]
            if top_line.product_id:
                top_product_name = top_line.product_id.display_name or ""
                top_product_id = top_line.product_id.id
                if top_line.product_id.categ_id:
                    top_category = top_line.product_id.categ_id.complete_name or top_line.product_id.categ_id.name or ""
            product_list = [l.product_id.display_name for l in self.lines if l.product_id][:5]

        currency = self.currency_id.name if self.currency_id else ""

        return {
            'customer_name': customer_name,
            'top_product': top_product_name,
            'top_product_id': top_product_id,
            'top_category': top_category,
            'total': "%.2f" % (self.amount_total or 0.0),
            'currency': currency,
            'product_list': ", ".join(product_list),
        }

    def _xibo_render_thanks_message(self, precomputed_ctx=None):
        """Try AI first; fall back to the template.

        :param precomputed_ctx: caller-supplied context dict (optional).
                                When provided, we re-use it instead of
                                computing it again, guaranteeing the AI and
                                the URL-render placeholders see the same
                                values.
        """
        self.ensure_one()
        config = self.config_id
        ctx = precomputed_ctx if precomputed_ctx is not None else self._xibo_collect_thanks_context()

        if config.xibo_thanks_use_ai:
            try:
                msg = self._xibo_call_ai(ctx)
                if msg:
                    return msg.strip()
            except Exception as e:
                _logger.warning("AI thank-you generation failed for order %s: %s",
                                self.name, e)
        # Fallback
        try:
            return (config.xibo_thanks_fallback_text or "Thanks, {customer_name}!").format(**ctx)
        except Exception:
            return f"Thanks, {ctx.get('customer_name', '')}!"

    def _xibo_call_ai(self, ctx):
        """Generate the Thank-You message via Odoo's native AI engine.

        We do NOT call any LLM provider directly. Instead we:

        1. Write the context (customer, top_product, summary) into 3 readonly
           fields on this pos.order.
        2. Invoke the bundled ``ir.actions.server`` with
           ``evaluation_type='ai_computed'`` (XML id
           ``xibo_connector_pos.action_pos_thanks_ai_compute``). That action
           is configured with ``update_field_id`` pointing at
           ``xibo_thanks_ai_message`` and a prompt template that references
           our 3 fields via ``<span data-ai-field="...">`` placeholders.
        3. Odoo routes the prompt to whichever LLM provider the customer
           has configured (OpenAI key today, Gemini/Anthropic/Mistral
           tomorrow when Odoo adds them) — this module stays
           provider-agnostic.
        4. The action writes the result into ``xibo_thanks_ai_message`` on
           THIS record. We read it back and return it.

        Returns the generated text on success, or ``None`` if the AI engine
        is unavailable or fails (caller falls back to the static template).
        """
        self.ensure_one()
        config = self.config_id

        # Render the user-prompt template (xibo_thanks_ai_prompt on pos.config)
        # with the variables from ctx. We push the rendered prompt into
        # `xibo_thanks_summary` so the AI server action can pick it up via its
        # `<span data-ai-field="xibo_thanks_summary">` placeholder.
        try:
            rendered_prompt = (config.xibo_thanks_ai_prompt or "").format(**ctx)
        except Exception as e:
            _logger.warning("[XIBO POS THANKS] bad prompt template (order=%s): %s",
                            self.name, e)
            return None
        if not rendered_prompt:
            _logger.info("[XIBO POS THANKS] empty prompt — skipping AI call")
            return None

        # Step 1: store context fields so the server action sees them.
        # `xibo_thanks_summary` carries the FULLY-RENDERED prompt body; the
        # action's ai_update_prompt only wraps it with output rules.
        self.sudo().write({
            'xibo_thanks_customer': ctx.get('customer_name') or '',
            'xibo_thanks_top_product': ctx.get('top_product') or '',
            'xibo_thanks_summary': rendered_prompt[:2000],  # safety cap
            'xibo_thanks_ai_message': False,  # clear any previous value
        })
        # Make sure the values are visible to whatever cursor the AI action
        # opens internally (it may use a separate env / sudo()).
        self.flush_recordset([
            'xibo_thanks_customer',
            'xibo_thanks_top_product',
            'xibo_thanks_summary',
            'xibo_thanks_ai_message',
        ])

        # Step 2: resolve & invoke the bundled AI server action.
        try:
            action = self.env.ref(
                'xibo_connector_pos.action_pos_thanks_ai_compute',
                raise_if_not_found=False,
            )
        except Exception as e:
            _logger.warning("[XIBO POS THANKS] could not resolve AI action xmlid (order=%s): %s",
                            self.name, e)
            return None
        if not action:
            _logger.info("[XIBO POS THANKS] AI action xmlid not found "
                         "(module not fully upgraded?) — falling back")
            return None

        _logger.info("[XIBO POS THANKS] invoking native AI server action "
                     "(order=%s, action=%s)", self.name, action.id)
        try:
            action.sudo().with_context(
                active_model='pos.order',
                active_id=self.id,
                active_ids=[self.id],
            ).run()
        except Exception as e:
            _logger.warning("[XIBO POS THANKS] native AI invocation FAILED "
                            "(order=%s): %s", self.name, e)
            return None

        # Step 3: read the AI-written field back.
        self.sudo().invalidate_recordset(['xibo_thanks_ai_message'])
        result = (self.xibo_thanks_ai_message or '').strip()
        # Some LLMs wrap the message in quotes.
        result = result.strip('"').strip("'").strip()
        if not result:
            _logger.info("[XIBO POS THANKS] native AI returned empty result "
                         "(order=%s) — falling back to template", self.name)
            return None
        _logger.info("[XIBO POS THANKS] native AI ok (order=%s): %r",
                     self.name, result[:120])
        return result

    def _xibo_send_thanks(self):
        """Send the thank-you broadcast (sync, called from async wrapper).

        Dispatches between two paths:
          * **Camino B** (preferred when configured): direct XMR via
            ``pos.config._xibo_activate_thanks_layout``. Pushes the message
            to the DataSet and switches the target screens to the Thank-You
            Layout for ``xibo_thanks_duration`` seconds; Xibo auto-reverts.
          * **Camino A** (legacy fallback): uses the ``xibo.broadcast`` model
            with ``quick_send``. Triggered when ``xibo_thanks_display_ids``
            is empty.
        """
        self.ensure_one()
        if not self._xibo_should_send_thanks():
            return False
        config = self.config_id
        # Build the context ONCE: re-using it for both AI rendering and
        # URL-render placeholder substitution avoids inconsistent values.
        ctx = self._xibo_collect_thanks_context()
        message = self._xibo_render_thanks_message(precomputed_ctx=ctx)
        if not message:
            _logger.info("[XIBO POS THANKS] no message rendered for order %s", self.name)
            return False

        _logger.info(
            "[XIBO POS THANKS] order=%s partner=%s total=%s msg=%r",
            self.name,
            self.partner_id.name if self.partner_id else '<guest>',
            self.amount_total, (message or '')[:80],
        )

        # URL-render flow: picked when the config has dedicated target
        # screens AND a Thank-You Layout. (Since v19.0.1.5.27 the DataSet
        # is no longer used — the Thank-You Layout must contain a Webpage
        # widget pointing at /xibo/thanks/<config_id>.)
        use_camino_b = bool(config.xibo_thanks_display_ids and config.xibo_thanks_layout_id)

        success = False
        if use_camino_b:
            _logger.info("[XIBO POS THANKS] using URL-render flow for order %s", self.name)
            try:
                success = bool(config._xibo_activate_thanks_layout(self, message, ctx=ctx))
            except Exception as e:
                _logger.exception(
                    "[XIBO POS THANKS] URL-render flow FAILED for order %s: %s",
                    self.name, e,
                )
                success = False
        else:
            _logger.info("[XIBO POS THANKS] using Camino A (legacy Broadcast) for order %s", self.name)
            success = self._xibo_send_thanks_via_broadcast(message)

        # Mark sent so the create()+write() double-fire does not duplicate.
        # We mark even on failure to avoid retry storms; the audit trail in
        # xibo.event.log is the source of truth for what happened.
        try:
            self.sudo().write({'xibo_thanks_sent': True})
        except Exception as e:
            _logger.warning(
                "[XIBO POS THANKS] could not set xibo_thanks_sent flag on order %s: %s",
                self.name, e,
            )
        return success

    def _xibo_send_thanks_via_broadcast(self, message):
        """Camino A — legacy broadcast path. Kept for backwards compatibility
        when ``xibo_thanks_display_ids`` is not configured."""
        self.ensure_one()
        config = self.config_id
        Broadcast = self.env['xibo.broadcast'].sudo()
        try:
            if config.xibo_thanks_dataset_id:
                # Use the dataset path (the layout reads from the dataset)
                Broadcast.quick_send(
                    server=config.xibo_server_id,
                    mode='ticker',
                    dataset=config.xibo_thanks_dataset_id,
                    values={
                        'message': message,
                        'name': self.partner_id._xibo_resolve_display_name() if self.partner_id else _("valued customer"),
                        'product': self._xibo_collect_thanks_context().get('top_product', ''),
                    },
                    displays=config.xibo_display_ids,
                    display_groups=config.xibo_display_group_ids,
                    duration=config.xibo_thanks_duration or 15,
                    origin=('pos.order', self.id, _('Thank-you (AI)')),
                    name=_('POS thanks: %s') % (self.partner_id.name if self.partner_id else 'guest'),
                )
            elif config.xibo_thanks_layout_id:
                # Use the static layout (message will not be on screen, just the layout)
                Broadcast.quick_send(
                    server=config.xibo_server_id,
                    mode='overlay',
                    layout=config.xibo_thanks_layout_id,
                    displays=config.xibo_display_ids,
                    display_groups=config.xibo_display_group_ids,
                    duration=config.xibo_thanks_duration or 15,
                    origin=('pos.order', self.id, _('Thank-you')),
                    name=_('POS thanks'),
                )
            else:
                return False
        except Exception as e:
            _logger.warning(
                "[XIBO POS THANKS] Camino A broadcast FAILED for order %s: %s",
                self.name, e,
            )
            return False
        return True

    def _xibo_send_thanks_async(self):
        """Schedule the thank-you broadcast to fire AFTER the current
        transaction commits, then run in a background thread so the cashier
        UI doesn't wait for AI + XMR latency.

        Why post-commit: when pos.order.create() or write(state=paid) is
        running, the new/updated row is invisible to other transactions
        until the current one commits. If we start a background thread
        right away (with its own cursor), the thread sees ``order.exists()
        == False`` and aborts. ``cr.postcommit.add(callback)`` defers the
        thread launch until the parent transaction has actually committed,
        at which point the order is durably visible to any cursor.
        """
        self.ensure_one()
        order_id = self.id
        order_name = self.name
        db_name = self.env.cr.dbname
        _logger.info("[XIBO POS THANKS] post-commit scheduled for order=%s (id=%s, db=%s)",
                     order_name, order_id, db_name)

        def _launch_thread():
            _logger.info("[XIBO POS THANKS] post-commit fired — launching thread for order_id=%s", order_id)
            threading.Thread(
                target=_runner,
                args=(db_name, order_id),
                daemon=True,
            ).start()

        def _runner(_db_name, _order_id):
            # Small delay lets the cashier UI finish painting before we
            # potentially log heavy AI / network activity to the same DB.
            time.sleep(0.2)
            _logger.info("[XIBO POS THANKS] async runner ENTERED for order_id=%s", _order_id)
            try:
                # Odoo 17+ removed Environment.manage(); just open a cursor
                # against the Registry and build an Environment.
                import odoo
                registry = odoo.modules.registry.Registry(_db_name)
                with registry.cursor() as cr:
                    # === Isolation level: READ COMMITTED ===
                    # Odoo opens every cursor in REPEATABLE READ, which takes
                    # the transaction snapshot at the FIRST statement. That
                    # broke the dedup below: the loser of the race took its
                    # snapshot while waiting for the advisory lock — i.e.
                    # BEFORE the winner committed — so it still read
                    # xibo_thanks_sent = FALSE, sent the message a second
                    # time, and then died on `could not serialize access due
                    # to concurrent update` when it wrote the flag.
                    #
                    # Under READ COMMITTED each statement takes a fresh
                    # snapshot, so after the lock is granted we see the
                    # winner's committed flag and step aside cleanly. This
                    # MUST be the first statement of the transaction.
                    cr.execute("SET TRANSACTION ISOLATION LEVEL READ COMMITTED")

                    # === Concurrency lock (PostgreSQL advisory lock) ===
                    # Both pos.order.create() AND write(state=paid) schedule
                    # the same callback, so up to two threads will race here.
                    #
                    # We use ``pg_advisory_xact_lock(key)`` — a lightweight
                    # session-bound lock that doesn't interact with row
                    # versioning and therefore does NOT trigger
                    # ``could not serialize access due to concurrent update``
                    # under REPEATABLE READ isolation (Odoo's default).
                    #
                    # The lock key is derived from the order id so threads
                    # racing on DIFFERENT orders never block each other.
                    # We use a 64-bit lock key namespaced under a stable
                    # constant prefix to avoid collisions with locks used
                    # by core Odoo or other modules.
                    LOCK_NAMESPACE = 0x71B0  # 'xibo' arbitrary 16-bit ns
                    lock_key = (LOCK_NAMESPACE << 48) | (_order_id & 0xFFFFFFFFFFFF)
                    cr.execute("SELECT pg_advisory_xact_lock(%s)", (lock_key,))

                    # === Claim the order, atomically ===
                    # One statement both checks the dedup flag and marks the
                    # order as taken. Whoever gets a row back owns the
                    # broadcast; everybody else exits without touching the
                    # row, so no second writer can hit a write conflict.
                    # Raw SQL keeps this out of the ORM cache and away from
                    # the AI server action, which writes to this row too.
                    cr.execute(
                        "UPDATE pos_order SET xibo_thanks_sent = TRUE "
                        "WHERE id = %s AND xibo_thanks_sent IS NOT TRUE "
                        "RETURNING id",
                        (_order_id,),
                    )
                    if not cr.fetchone():
                        cr.execute(
                            "SELECT xibo_thanks_sent FROM pos_order WHERE id = %s",
                            (_order_id,),
                        )
                        row = cr.fetchone()
                        if not row:
                            _logger.warning(
                                "[XIBO POS THANKS] async runner: order_id=%s not "
                                "found in DB (unexpected after post-commit)",
                                _order_id,
                            )
                        else:
                            _logger.info(
                                "[XIBO POS THANKS] async runner: order_id=%s "
                                "already sent (lost the race) — skipping",
                                _order_id,
                            )
                        return

                    env = odoo.api.Environment(cr, odoo.SUPERUSER_ID, {})
                    # Invalidate any cached value of the flag from the new
                    # env, so when _xibo_send_thanks (or its helpers) read
                    # the field they don't get a stale False.
                    env['pos.order'].invalidate_model(['xibo_thanks_sent'])
                    order = env['pos.order'].browse(_order_id).with_context(
                        xibo_skip_sent_check=True,
                    )
                    _logger.info(
                        "[XIBO POS THANKS] async runner calling _xibo_send_thanks "
                        "for order=%s state=%s",
                        order.name, order.state,
                    )
                    order._xibo_send_thanks()
                    # The flag was already set up-front, so the redundant
                    # write inside _xibo_send_thanks is a no-op. Commit
                    # releases the advisory lock.
                    cr.commit()
            except Exception as e:
                _logger.exception(
                    "[XIBO POS THANKS] Async runner crashed for order_id=%s: %s",
                    _order_id, e,
                )

        # Register the launcher on the post-commit queue of the current
        # cursor. If the transaction rolls back, the callback is never run.
        self.env.cr.postcommit.add(_launch_thread)

    # States in which an order is worth a Thank-You.
    _XIBO_THANKS_STATES = ('paid', 'done', 'invoiced')

    @api.model_create_multi
    def create(self, vals_list):
        orders = super().create(vals_list)
        # Only orders that are ALREADY payable-complete are worth scheduling.
        # A draft order will come back through write(state=paid) later; if we
        # scheduled it here too, both hooks would race for the same order.
        due = orders.filtered(lambda o: o.state in self._XIBO_THANKS_STATES)
        _logger.info("[XIBO POS THANKS] pos.order.create() hook fired: %s order(s) created, %s to notify",
                     len(orders), len(due))
        for o in due:
            try:
                o._xibo_send_thanks_async()
            except Exception as e:
                _logger.warning("[XIBO POS THANKS] async scheduling failed in create: %s", e)
        return orders

    def write(self, vals):
        # Which records actually TRANSITION into a thank-you state — read
        # before super(), while the old value is still there. Re-saving an
        # order that is already paid used to schedule a second broadcast for
        # nothing.
        entering = self.browse()
        if vals.get('state') in self._XIBO_THANKS_STATES:
            entering = self.filtered(lambda o: o.state != vals['state'])
        result = super().write(vals)
        if entering:
            _logger.info("[XIBO POS THANKS] pos.order.write() hook fired: state→%s for %s order(s) (ids=%s)",
                         vals['state'], len(entering), entering.ids)
            for o in entering:
                try:
                    o._xibo_send_thanks_async()
                except Exception as e:
                    _logger.warning("[XIBO POS THANKS] async scheduling failed in write: %s", e)
        return result
