{
    "name": "Jewelry Repairs & Workshop",
    "version": "19.0.1.2.0",
    "category": "Inventory/Repair",
    "summary": "Customer piece custody, typed intake photos, signatures, jeweler dispatch, scrap control and QC on top of Odoo Repairs",
    "author": "XUBAX",
    "website": "https://www.xubax.com",
    "license": "OPL-1",
    "price": 179.0,
    "currency": "USD",
    "depends": [
        "repair",
        "sale_management",
        "account",
        "stock",
        "mail",
        "portal",
    ],
    "data": [
        "security/xb_jewelry_groups.xml",
        "security/ir.model.access.csv",
        "security/xb_jewelry_portal_rules.xml",
        "data/ir_sequence_data.xml",
        "data/xb_jewelry_photo_kind_data.xml",
        "views/xb_jewelry_piece_views.xml",
        "views/xb_jewelry_photo_kind_views.xml",
        "views/xb_metal_purity_views.xml",
        "views/xb_jewelry_dispatch_views.xml",
        "views/xb_jeweler_settlement_views.xml",
        "views/repair_order_views.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
        "views/xb_jewelry_menus.xml",
        "report/xb_jewelry_reports.xml",
        "report/xb_jewelry_intake_templates.xml",
        "views/xb_jewelry_portal_templates.xml",
        "views/xb_jewelry_photo_link_templates.xml",
    ],
    "images": ["static/description/banner.png"],
    "installable": True,
    "application": False,
}
