from . import product_category
from . import xb_jewelry_photo_kind
from . import xb_metal_purity
from . import xb_jewelry_photo
from . import xb_jewelry_piece
from . import xb_jewelry_dispatch
from . import xb_jeweler_rate
from . import xb_jeweler_settlement
from . import repair_order
from . import repair_order_photo_link
from . import res_partner
from . import res_company
from . import res_config_settings
