# -*- coding: utf-8 -*-
import logging

from . import models
from . import controllers

_logger = logging.getLogger(__name__)


# =============================================================================
# Pre-init hook: defensive schema validation
# =============================================================================
#
# When this module is upgraded in-place (the customer drops new files into the
# addons folder and restarts Odoo, without going through "Apps -> Upgrade"),
# Odoo loads the new Python code but does NOT run schema migrations. This
# leaves an inconsistent state: the model declares new fields, but the
# physical columns do not exist on the table. Any read of those fields then
# raises ``psycopg2.errors.UndefinedColumn`` in the user's face.
#
# We close that window here. ``pre_init_hook`` runs before Odoo's normal
# table-creation step on install/upgrade, and is the perfect place to ensure
# every column declared on the latest version exists on disk — even if Odoo's
# own upgrade machinery didn't catch the version bump.
#
# All ALTER TABLE statements use ``IF NOT EXISTS`` so re-running the hook is
# always safe (idempotent). The hook never blocks on errors: if a single
# column can't be added it logs and moves on, leaving Odoo's normal upgrade
# path to finish the job.
# =============================================================================

# Columns guaranteed to exist on pos_order after every install/upgrade.
# Format: (column_name, postgres_type, comment-for-future-reference).
_POS_ORDER_COLUMNS = [
    ('xibo_thanks_sent', 'BOOLEAN DEFAULT FALSE',
     'Anti-double-dispatch flag for the Thank-You broadcast.'),
    ('xibo_thanks_customer', 'VARCHAR',
     'Customer display name captured at payment time.'),
    ('xibo_thanks_top_product', 'VARCHAR',
     'Most expensive product in the order.'),
    ('xibo_thanks_summary', 'VARCHAR',
     'Compact one-line summary of the order context for the AI prompt.'),
    ('xibo_thanks_ai_message', 'VARCHAR',
     'The Thank-You message generated by Odoo native AI engine.'),
]

# Columns guaranteed to exist on pos_config.
_POS_CONFIG_COLUMNS = [
    ('xibo_thanks_preset', "VARCHAR DEFAULT 'minimal'",
     'Visual preset of the Thank-You page (minimal/warm/bold/custom).'),
    ('xibo_thanks_custom_html', 'TEXT',
     'Custom HTML template when preset is custom.'),
    ('xibo_thanks_show_product_image', 'BOOLEAN DEFAULT FALSE',
     'Whether to include the top product image in the Thank-You page.'),
    # ---- Audio settings (since v1.5.31) ----
    ('xibo_thanks_audio_enabled', 'BOOLEAN DEFAULT FALSE',
     'Whether to play an audio notification when the Thank-You appears.'),
    ('xibo_thanks_audio_preset', "VARCHAR DEFAULT 'chime'",
     'Built-in audio preset name (chime/cash/success/bell) or "custom".'),
    ('xibo_thanks_audio_custom_url', 'VARCHAR',
     'Absolute URL to a custom audio file (mp3, wav, ogg). Used when '
     'xibo_thanks_audio_preset = custom.'),
    ('xibo_thanks_audio_volume', 'INTEGER DEFAULT 80',
     'Audio volume 0-100. Default 80.'),
    # ---- Thank-You URL access key (since v1.5.33) ----
    ('xibo_thanks_token', 'VARCHAR',
     'Secret key embedded in the Thank-You URL when require_token is on.'),
    ('xibo_thanks_require_token', 'BOOLEAN DEFAULT FALSE',
     'When TRUE, /xibo/thanks/<id> requires ?key=<token>. Default FALSE so '
     'existing screens keep working until their URL is updated.'),
]


def _ensure_columns(cr, table, columns):
    """Add any missing column to ``table``. Idempotent."""
    cr.execute(
        "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
        (table,),
    )
    if not cr.fetchone():
        _logger.info("[XIBO POS PRE-INIT] table %s not found yet; skipping", table)
        return

    cr.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = %s",
        (table,),
    )
    existing = {row[0] for row in cr.fetchall()}

    added = 0
    for name, pg_type, comment in columns:
        if name in existing:
            continue
        try:
            cr.execute(
                'ALTER TABLE "%s" ADD COLUMN IF NOT EXISTS "%s" %s'
                % (table, name, pg_type)
            )
            added += 1
            _logger.info(
                "[XIBO POS PRE-INIT] added column %s.%s (%s)",
                table, name, pg_type,
            )
        except Exception as e:
            # Don't crash the upgrade. Log it and let Odoo's own machinery
            # try again on the next pass.
            _logger.warning(
                "[XIBO POS PRE-INIT] could not add %s.%s: %s",
                table, name, e,
            )
    if added:
        _logger.info(
            "[XIBO POS PRE-INIT] %s: added %s column(s) defensively",
            table, added,
        )


def pre_init_check_schema(env_or_cr):
    """Pre-init hook entrypoint. Defensive schema validation.

    Called by Odoo before this module's normal install/upgrade routine.
    Accepts either an Environment (Odoo 17+) or a cursor (older Odoo) — we
    detect at runtime and adapt.
    """
    # Odoo 17+ passes ``env``; older versions pass ``cr``.
    cr = getattr(env_or_cr, 'cr', env_or_cr)
    try:
        _logger.info("[XIBO POS PRE-INIT] checking schema consistency...")
        _ensure_columns(cr, 'pos_order', _POS_ORDER_COLUMNS)
        _ensure_columns(cr, 'pos_config', _POS_CONFIG_COLUMNS)
        _logger.info("[XIBO POS PRE-INIT] schema check complete")
    except Exception as e:
        # Even if everything fails, never break the upgrade.
        _logger.exception(
            "[XIBO POS PRE-INIT] hook failed (non-fatal, upgrade continues): %s",
            e,
        )
